#!/bin/bash
read PARAM
SWEEK=$(echo $PARAM | cut -d: -f1)
SDAY=$(echo $PARAM | cut -d: -f2)
EWEEK=$(echo $PARAM | cut -d: -f3)
EDAY=$(echo $PARAM | cut -d: -f4)
FILES=
W=$SWEEK
while [ $W -le $EWEEK ]
do
	if [ $W -eq $SWEEK ]
	then
		D=$SDAY
	else
		D=0
	fi
	if [ $W -eq $EWEEK ]
	then
		X=$EDAY
	else
		X=6
	fi
	while [ $D -le $X ]
	do
		FILES="$FILES _history/$W/$D/history_data"
		(( D = D + 1 ))
	done
	(( W = W + 1 ))
done

echo "Content-type: text/plain"
echo ""
for i in $FILES
do
	if [ -e $i ]
	then
		cat $i
	fi
done
